services:
  next:
    image: ghcr.io/leeapril0612/jangPyeong:latest

    container_name: next-app

    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
